pom.xml, src/main/webapp/WEB-INF/web.xml
=> [FIX] web.xml 파일 servlet 에 맞춰 변경

pom.xml, src/main/webapp/WEB-INF/spring/appServlet/dao-context.xml
PostgreSQL 관련 의존성 추가 
dao-context.xml 관련 설정 추가
dao는 shared bean 으로 사용할 예정입니다.
=> [ADD] PostgreSQL 관련 의존성 추가, dao-context.xml 관련 설정 추가

src/main/java/com/bkc/main/controller/HomeController.java, src/main/webapp/WEB-INF/props/jdbc.properties, src/main/webapp/WEB-INF/spring/appServlet/dao-context.xml
=> [UPDATE] dao-context.xml 수정

src/main/webapp/resources/css/delivery/delivery.css
깃허브 팀 프로젝트 제대로 되는지 확인해보기 위해서 지금 진행중인 delivery.css를 올립니다.
=> [INITIAL] - 브랜치가 제대로 나눠지는지 확인 위해서 delivery.css를 올립니다.

src/main/webapp/WEB-INF/views/include/footer/main_desktop_footer.jsp, src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/WEB-INF/views/subpages/brand/newsNewItem.jsp, src/main/webapp/WEB-INF/views/subpages/brand/story.jsp, src/main/webapp/WEB-INF/views/subpages/brand/whybkc.jsp, src/main/webapp/resources/css/include/main-gnb.css, src/main/webapp/resources/css/main/main.css, src/main/webapp/resources/css/subpages/brand/newsNewItemview.css, src/main/webapp/resources/css/subpages/brand/storyview.css, src/main/webapp/resources/css/subpages/brand/whybkcview.css
[UPDATE] main페이지 footer 관련 추가 밑에 footer menu footer로 묶음 
[STYLE] brand 내부 페이지 스타일 변경 추후 작업 더 필요
brand 클래스 재설정 필요
=> [UPDATE] main페이지 footer 관련 추가 밑에 footer menu footer로 묶음 

src/main/java/com/bkc/menuInform/controller/MenuInformController.java, src/main/webapp/WEB-INF/views/include/header/main_desktop_header.jsp, src/main/webapp/WEB-INF/views/subpages/map/store.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/beerZone.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/chickenMenu.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/sideMenu.jsp, src/main/webapp/resources/css/subpages/menuInform/menuInform.css, src/main/webapp/resources/js/subpages/menuInform/menuInform.js
[FIX] jquery가 두개가 설정되어 있어서 하나만 설정
[ADD] menuInform폴덩의 모든 페이지에 해당하는 css js추가
[ADD] 치킨메뉴를 누르면 나오는 chickenMenu.jsp 추가
[ADD] 비어존 메뉴를 누르면 나오는 beerZone.jsp 추가
[ADD] 사이드 메뉴를 누르면 나오는 sideMenu.jsp 추가
[UPDATE] 헤더에서 치킨메뉴/ 사이드메뉴/ 비어존 메뉴를 누르면 해당 페이지로 가게 경로 추가
[ADD] menuInform폴더에서 해당 페이지.do로 갈 수 있게 컨트롤러 작성, MenuInformController
=> menuInform에 필요한 페이지 추가 했습니다.

src/main/java/com/bkc/menuInform/controller/MenuInformController.java, src/main/java/com/bkc/menuInform/dao/SideMenuDAO.java, src/main/java/com/bkc/menuInform/dao/SideMenuDAOImpl.java, src/main/java/com/bkc/menuInform/service/SideMenuService.java, src/main/java/com/bkc/menuInform/service/SideMenuServiceImpl.java, src/main/java/com/bkc/menuInform/vo/SideMenuVO.java, src/main/resources/mapper/sidemenu-mapping.xml, src/main/resources/mybatis-config.xml, src/main/webapp/WEB-INF/views/subpages/menuInform/chickenMenu.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/sideMenu.jsp
=> [UPDATE] 사이드메뉴 조회

src/main/webapp/resources/css/subpages/menuInform/menuInform.css
=> [STYLE] menuInform.css 변경

src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/resources/css/main/main.css
[FIX] index 페이지 슬라이더랑 유튜브 사이 간격 조정, 버튼 탑 버튼 추가
=> [FIX] index 페이지 슬라이더랑 유튜브 사이 간격 조정, 버튼 탑 버튼 추가

src/main/java/com/bkc/customerService/controller/FaqController.java, src/main/java/com/bkc/customerService/dao/FaqDAO.java, src/main/java/com/bkc/customerService/dao/FaqDAOImpl.java, src/main/java/com/bkc/customerService/service/FaqService.java, src/main/java/com/bkc/customerService/service/FaqServiceImpl.java, src/main/java/com/bkc/customerService/vo/FaqVO.java, src/main/resources/mapper/faq-mapping.xml, src/main/resources/mybatis-config.xml, src/main/webapp/WEB-INF/views/subpages/customerService/faq.jsp, src/main/webapp/resources/css/subpages/customerService/faq.css, src/main/webapp/resources/js/customerService/cs.js
=> Feature jinwon

src/main/webapp/WEB-INF/views/subpages/menuInform/beerzonedetail.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/sidemenudetail.jsp
=> [FIX] 페이지에 잘못된 부분 수정

src/main/webapp/WEB-INF/views/subpages/menuInform/beerzonedetail.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/chickenmenudetail.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/sidemenudetail.jsp, src/main/webapp/resources/css/subpages/menuInform/menuInformdetail.css
=> [FIX] 슬릭이 제대로 안나와서 수정했습니다

src/main/java/com/bkc/admin/board/term/controller/TermController.java, src/main/java/com/bkc/admin/board/term/dao/TermPrivacyDAO.java, src/main/java/com/bkc/admin/board/term/dao/TermPrivacyDAOImpl.java, src/main/java/com/bkc/admin/board/term/service/TermPrivacyService.java, src/main/java/com/bkc/admin/board/term/service/TermPrivacyServiceImpl.java, src/main/java/com/bkc/admin/board/term/vo/TermPrivacyVO.java, src/main/resources/mapper/admin-termPrivacy-mapping.xml, src/main/resources/mybatis-config.xml, src/main/webapp/WEB-INF/views/include/footer/main_desktop_footer.jsp, src/main/webapp/WEB-INF/views/subpages/law/terms.jsp, src/main/webapp/WEB-INF/views/subpages/law/termsEmail.jsp, src/main/webapp/WEB-INF/views/subpages/law/termsPrivacy.jsp
[ADD] 개인정보취급방침 페이지 게시판 추가
[UPDATE] 개인정보 취급방침으로 가는 경로 조정
[UPDATE] 개인정보 취급방침으로 가는 경로 추가, jsp에서 필요없는 부분 제거
=> [ADD] 개인정보취급방침 페이지 게시판 추가

src/main/java/com/bkc/admin/board/notice/controller/AdminNoticeController.java, src/main/java/com/bkc/admin/board/notice/dao/AdminNoticeDAO.java, src/main/java/com/bkc/admin/board/notice/dao/AdminNoticeDAOImpl.java, src/main/java/com/bkc/admin/board/notice/service/AdminNoticeService.java, src/main/java/com/bkc/admin/board/notice/service/AdminNoticeServiceImpl.java, src/main/java/com/bkc/customerService/controller/NoticeController.java, src/main/java/com/bkc/customerService/dao/NoticeDAO.java, src/main/java/com/bkc/customerService/dao/NoticeDAOImpl.java, src/main/java/com/bkc/customerService/service/NoticeService.java, src/main/java/com/bkc/customerService/service/NoticeServiceImpl.java, src/main/java/com/bkc/customerService/vo/NoticeVO.java, src/main/java/com/bkc/customerService/vo/PageMaker.java, src/main/java/com/bkc/customerService/vo/SearchVO.java, src/main/resources/mapper/admin-notice-mapping.xml, src/main/resources/mapper/notice-mapping.xml, src/main/webapp/WEB-INF/views/admin/subpages/notice/getNotice.jsp, src/main/webapp/WEB-INF/views/admin/subpages/notice/insertNotice.jsp, src/main/webapp/WEB-INF/views/admin/subpages/notice/noticelist.jsp, src/main/webapp/WEB-INF/views/admin/subpages/notice/updateNotice.jsp, src/main/webapp/WEB-INF/views/include/footer/main_desktop_footer.jsp, src/main/webapp/WEB-INF/views/subpages/customerService/getNotice.jsp, src/main/webapp/WEB-INF/views/subpages/customerService/notice.jsp, src/main/webapp/resources/css/subpages/customerService/getNotice.css, src/main/webapp/resources/css/subpages/customerService/notice.css
[UPDATE], [ADD] 사용자 공지사항 검색 기능 추가 및 페이징 처리, 내용 수정
[ADD] 관리자 공지사항 게시판 추가
=> 공지사항 추가 및 수정

src/main/java/com/bkc/admin/board/term/controller/TermController.java, src/main/java/com/bkc/admin/board/term/dao/TermDAO.java, src/main/java/com/bkc/admin/board/term/dao/TermDAOImpl.java, src/main/java/com/bkc/admin/board/term/service/TermService.java, src/main/java/com/bkc/admin/board/term/service/TermServiceImpl.java, src/main/resources/mapper/admin-term-mapping.xml, src/main/webapp/WEB-INF/views/admin/include/secondHeader.jsp, src/main/webapp/WEB-INF/views/admin/subpages/law/terms.jsp, src/main/webapp/WEB-INF/views/admin/subpages/law/updateTerms.jsp
[ADD] 관리자 이용약관 상세페이지, 수정페이지 완료
=> [ADD] 관리자 이용약관 상세페이지, 수정페이지 완료

src/main/java/com/bkc/admin/board/term/controller/TermController.java, src/main/java/com/bkc/admin/board/term/dao/TermDAO.java, src/main/java/com/bkc/admin/board/term/dao/TermEmailDAO.java, src/main/java/com/bkc/admin/board/term/dao/TermEmailDAOImpl.java, src/main/java/com/bkc/admin/board/term/dao/TermPrivacyDAO.java, src/main/java/com/bkc/admin/board/term/dao/TermPrivacyDAOImpl.java, src/main/java/com/bkc/admin/board/term/service/TermEmailService.java, src/main/java/com/bkc/admin/board/term/service/TermEmailServiceImpl.java, src/main/java/com/bkc/admin/board/term/service/TermPrivacyService.java, src/main/java/com/bkc/admin/board/term/service/TermPrivacyServiceImpl.java, src/main/resources/mapper/admin-termEmail-mapping.xml, src/main/resources/mapper/admin-termPrivacy-mapping.xml, src/main/webapp/WEB-INF/views/admin/include/secondHeader.jsp, src/main/webapp/WEB-INF/views/admin/subpages/law/terms.jsp, src/main/webapp/WEB-INF/views/admin/subpages/law/termsEmail.jsp, src/main/webapp/WEB-INF/views/admin/subpages/law/termsPrivacy.jsp, src/main/webapp/WEB-INF/views/admin/subpages/law/updateTermsEmail.jsp, src/main/webapp/WEB-INF/views/admin/subpages/law/updateTermsPrivacy.jsp
[UPDATE] 이메일약관과 개인정보 취급방침으로 가는 경로 추가
[UPDATE] 관리자 이메일약관 컨트롤러와 관리자 개인정보취급방침 컨트롤러 추가
[STYLE] 파비콘 추가
[FIX] 잘못된 import 제거
[ADD] 관리자 이메일약관 페이지 완료
[ADD] 관리자 개인정보취급 방침 페이지 완료
=> [ADD] 관리자 이메일약관 페이지 완료, 관리자 개인정보취급방침 페이지 완료

src/main/java/com/bkc/delivery/controller/DeliveryController.java, src/main/webapp/WEB-INF/views/delivery/delivery.jsp, src/main/webapp/WEB-INF/views/delivery/orderList.jsp, src/main/webapp/WEB-INF/views/include/header/delivery_desktop_header2.jsp, src/main/webapp/resources/css/delivery/delivery2.css, src/main/webapp/resources/css/delivery/orderList.css, src/main/webapp/resources/css/include/delivery-gnb2.css, src/main/webapp/resources/js/delivery/delivery2.js, src/main/webapp/resources/js/delivery/orderList.css
[ADD] 회원주문 페이지 추가
[UPDATE] 회원주문페이지 푸터 DB에서 받아올 수 있게 추가
[ADD] 새로운 회원주문 페이지에 대한 헤더 추가 및 헤더 푸터 CSS추가
=>  [ADD] 회원주문 페이지 추가

src/main/java/com/bkc/delivery/controller/DeliveryController.java, src/main/webapp/WEB-INF/views/delivery/mybkc.jsp, src/main/webapp/WEB-INF/views/delivery/orderDetail.jsp, src/main/webapp/WEB-INF/views/delivery/orderList.jsp, src/main/webapp/WEB-INF/views/include/header/delivery_desktop_header2.jsp, src/main/webapp/resources/css/delivery/mybkc.css, src/main/webapp/resources/js/delivery/mybkc.js
[ADD] mybkc 페이지 추가
[UPDATE] mybkc로 가는 경로 추가
=> [ADD] mybkc 페이지 추가

src/main/java/com/bkc/delivery/controller/DeliveryController.java, src/main/webapp/WEB-INF/views/delivery/mySet.jsp, src/main/webapp/WEB-INF/views/delivery/mybkc.jsp, src/main/webapp/resources/css/delivery/mySet.css, src/main/webapp/resources/js/delivery/mySet.js
[ADD] mybkc 페이지에서 들어갈 수 있는 mySet페이지 추가
[UPDATE] mySet페이지로 보내기 위한 경로 설정
=>  [ADD] mybkc 페이지에서 들어갈 수 있는 mySet페이지 추가

src/main/webapp/WEB-INF/views/delivery/cart.jsp, src/main/webapp/WEB-INF/views/include/header/delivery_desktop_header2.jsp, src/main/webapp/resources/css/delivery/cart.css, src/main/webapp/resources/js/delivery/cart.js
[ADD] cart 페이지 추가, 현재 헤더에서 카트 누를시 500번 현상 발생, 딜리버리페이지에서 해당 메뉴 누를때만 카트 페이지로 이동가능
=> [ADD] cart 페이지 추가

src/main/java/com/bkc/delivery/controller/DeliveryController.java, src/main/java/com/bkc/delivery/controller/OrderController.java, src/main/java/com/bkc/delivery/dao/OrderDAO.java, src/main/java/com/bkc/delivery/dao/OrderDAOImpl.java, src/main/java/com/bkc/delivery/service/OrderService.java, src/main/java/com/bkc/delivery/service/OrderServiceImpl.java, src/main/resources/mapper/order/order-list-mapping.xml, src/main/webapp/WEB-INF/views/include/header/delivery_desktop_header2.jsp
=> [UPDATE] 주문내역이 있을 경우 메뉴가 나타나고 주문내역이 없으면 "주문내역이 없습니다" 나타나게 구현

src/main/java/com/bkc/delivery/controller/DeliveryController.java, src/main/java/com/bkc/user/controller/GuestController.java, src/main/webapp/WEB-INF/views/delivery/login.jsp, src/main/webapp/WEB-INF/views/guest/guestCart.jsp, src/main/webapp/WEB-INF/views/guest/guestOrder.jsp, src/main/webapp/WEB-INF/views/guest/guestOrderComplete.jsp, src/main/webapp/WEB-INF/views/guest/guestOrderDetail.jsp, src/main/webapp/WEB-INF/views/guest/guestOrderList.jsp, src/main/webapp/WEB-INF/views/guest/guestdelivery.jsp, src/main/webapp/WEB-INF/views/include/header/guestdelivery_desktop_header.jsp, src/main/webapp/resources/css/guest/guestCart.css, src/main/webapp/resources/css/guest/guestOrder.css, src/main/webapp/resources/css/guest/guestOrderComplete.css, src/main/webapp/resources/css/guest/guestOrderDetail.css, src/main/webapp/resources/css/guest/guestOrderList.css, src/main/webapp/resources/js/guest/guestCart.js, src/main/webapp/resources/js/guest/guestOrder.js, src/main/webapp/resources/js/guest/guestOrderComplete.js, src/main/webapp/resources/js/guest/guestOrderDetail.js, src/main/webapp/resources/js/guest/guestOrderList.js
비회원 주문내역
비회원 주문상세
비회원 카트
비회원 주문하기
비회원 주문완료 페이지 추가
벡 작업 필요합니다.
=> [ADD] 비회원 딜리버리 페이지들 추가 (벡 작업 필요)

src/main/webapp/WEB-INF/views/delivery/delivery.jsp, src/main/webapp/WEB-INF/views/delivery/login.jsp, src/main/webapp/WEB-INF/views/delivery/mybkc.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/beerzonedetail.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/chickenmenudetail.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/newmenudetail.jsp, src/main/webapp/WEB-INF/views/subpages/menuInform/sidemenudetail.jsp
[DELETE] 알레르기 제거
[DELETE] 비회원 제거
=> [DELETE] 현재 사용 못하는 부분 제거
